In [1]:
import torch
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [2]:
print("torch version:", torch.__version__)
print("numpy version:", np.__version__)

torch version: 2.6.0+cu118
numpy version: 2.2.4


creating a 2x3 pytorch tensor with float32 datatype, assigns it to a specific device(CPU or GPU), and enabling gradient tracking for backpropagation

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print("device:", device)

device: cpu


In [4]:
my_tensor = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32, device=device, requires_grad=True)
print("my_tensor:", my_tensor)

print("Datatype:", my_tensor.dtype)
print("Device:", my_tensor.device)
print("Shape:", my_tensor.shape)
print("Requires Gradient:", my_tensor.requires_grad)

my_tensor: tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
Datatype: torch.float32
Device: cpu
Shape: torch.Size([2, 3])
Requires Gradient: True


creating an empty 3x3 tensor

In [5]:
x = torch.empty(3, 3)
print("Empty Tensor:", x)

Empty Tensor: tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


creating a tensor filled with zeros

In [6]:
x = torch.zeros(3, 3)
print("Zeros Tensor:", x)

Zeros Tensor: tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


creating a tensor filled with ones

In [7]:
z = torch.ones(3, 3)
print("Ones Tensor:", z)

Ones Tensor: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


creating a tensor with random values

In [8]:
x = torch.rand(3,3)
print("Random Tensor:", x)

Random Tensor: tensor([[0.4173, 0.1925, 0.5628],
        [0.4440, 0.1461, 0.3390],
        [0.7969, 0.4374, 0.0182]])


creating an identity matrix

In [9]:
x = torch.eye(4,4)
print("Identity Matrix:", x)

Identity Matrix: tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


create a tensor using arange

In [10]:
x = torch.arange(5)
print("Arange Tensor:", x)

Arange Tensor: tensor([0, 1, 2, 3, 4])


create a tensor using linspace

In [11]:
x = torch.linspace(0.1,1,5)
print("Linespace Tensor:", x)

Linespace Tensor: tensor([0.1000, 0.3250, 0.5500, 0.7750, 1.0000])


create a tensor with values drawn from a normal distribution

In [12]:
x = torch.empty(1,5).normal_(mean=0, std=1)
print("Normal Distribution Tensor:", x)

Normal Distribution Tensor: tensor([[0.3914, 1.3296, 0.0920, 1.6104, 0.3841]])


creating a tensor with values drawn from a uniform distribution

In [13]:
x = torch.empty(1,5).uniform_(0,1)
print("Uniform Distribution Tensor:", x)

Uniform Distribution Tensor: tensor([[0.8919, 0.7681, 0.2409, 0.2355, 0.1280]])


**Type conversion**
creating a tensor with values [0,1,2,3] and demonstrating type conversion to boolean, int16, int64, float16, float32 and float64

In [14]:
tensor = torch.arange(4)
print("Tensor:", tensor)

Tensor: tensor([0, 1, 2, 3])


In [15]:
print("Boolean Tensor:", tensor.bool())

Boolean Tensor: tensor([False,  True,  True,  True])


In [16]:
print("Short Tensor(int16):", tensor.short())
print("Long Tensor(int64):", tensor.long())

Short Tensor(int16): tensor([0, 1, 2, 3], dtype=torch.int16)
Long Tensor(int64): tensor([0, 1, 2, 3])


In [17]:
print("Half Tensor(float16):", tensor.half())
print("Float Tensor(float32):", tensor.float())
print("Double Tensor(float64):", tensor.double())

Half Tensor(float16): tensor([0., 1., 2., 3.], dtype=torch.float16)
Float Tensor(float32): tensor([0., 1., 2., 3.])
Double Tensor(float64): tensor([0., 1., 2., 3.], dtype=torch.float64)


**Converting between Numpy arrays and Tensors**
pytorch makes it easy to switch between Numpy arrays and tensors, allowing seamless integration with existing computing workflows.

In [18]:
np_array = np.zeros((5,5))
print("Numpy Array:\n", np_array)

Numpy Array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
tensor = torch.from_numpy(np_array)
print("Tensor from Numpy Array:\n", tensor)

Tensor from Numpy Array:
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)


In [20]:
numpy_back = tensor.numpy()
print("Numpy Array from Tensor:\n", numpy_back)

Numpy Array from Tensor:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


**Tensor Mathematics and Comparism operations**

In [21]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])
print(f"x:{x}  |  y:{y}")

x:tensor([1, 2, 3])  |  y:tensor([9, 8, 7])


*Addition*

In [22]:
z = x + y
print("Addition Results:", z)

Addition Results: tensor([10, 10, 10])


In [23]:
'''addition using .add'''
z1 = torch.empty(3)
torch.add(x,y, out=z1)
z2 = torch.add(x,y)
print("Addition Results using .add:", z,z1,z2)

Addition Results using .add: tensor([10, 10, 10]) tensor([10., 10., 10.]) tensor([10, 10, 10])


*Subtraction*

In [24]:
z = x - y
print("Subtraction Results:", z)

Subtraction Results: tensor([-8, -6, -4])


*Division (true division)*

In [25]:
z = torch.true_divide(x,y)
print("True Division Results:", z)

True Division Results: tensor([0.1111, 0.2500, 0.4286])


*Implace operations*

In [26]:
t = torch.ones(3)
print("Before implace addition:", t)
t.add_(x)
print("After implace addition:", t)
t += x # note: t = t + x creates a new tensor
print("After Second Implace addition:", t)

Before implace addition: tensor([1., 1., 1.])
After implace addition: tensor([2., 3., 4.])
After Second Implace addition: tensor([3., 5., 7.])


*Exponentiation*

In [27]:
z = x.pow(2)
print("Power Results (pow):", z)

Power Results (pow): tensor([1, 4, 9])


In [28]:
z = x ** 2
print("Power Results (**):", z)

Power Results (**): tensor([1, 4, 9])


*Comparisms*

In [29]:
z = x > 0
print("x > 0:", z)
z = z < 0
print("z < 0:", z)
z = x == 0
print("x == 0:", z)

x > 0: tensor([True, True, True])
z < 0: tensor([False, False, False])
x == 0: tensor([False, False, False])


*Dot Product*

In [30]:
z = torch.dot(x,y)
print("Dot Product:", z)

Dot Product: tensor(46)


**Matric Multiplication and Batch Operations**

*Matrix Multiplication uses @ or torch.mm()*

In [31]:
x2 = torch.tensor([[1,2,3]])
y2 = torch.tensor([[9,8,7]])

z = x2 @ torch.t(y2)
print("Matrix Multiplication(@ operator):\n", z)

z = torch.mm(x2, torch.t(y2))
print("Matrix Multiplication(mm function):\n", z)

Matrix Multiplication(@ operator):
 tensor([[46]])
Matrix Multiplication(mm function):
 tensor([[46]])


*Matrix exponentiation: multiplying a matrix with itself 3 times*

In [32]:
matrix_exp = torch.rand(5,5)
print("Matrix multiplied 3 times:\n", matrix_exp @ matrix_exp @ matrix_exp)
print("Matrix power 3:\n", matrix_exp.pow(3))

Matrix multiplied 3 times:
 tensor([[3.2337, 2.3459, 1.4537, 1.9789, 2.9064],
        [3.2327, 2.2860, 1.5220, 2.0166, 2.9165],
        [3.9123, 2.6739, 1.9726, 2.5762, 3.5469],
        [2.5836, 1.8868, 1.1257, 1.5439, 2.2998],
        [2.8673, 2.0340, 1.3484, 1.8206, 2.5435]])
Matrix power 3:
 tensor([[1.9910e-01, 2.3783e-01, 1.8204e-03, 7.4493e-02, 2.6085e-01],
        [3.4909e-01, 1.9370e-01, 9.2573e-03, 2.7865e-05, 4.9173e-01],
        [1.0990e-01, 8.5300e-04, 5.6758e-01, 2.1063e-01, 5.2858e-01],
        [3.5436e-01, 1.2079e-01, 8.2032e-06, 8.9122e-03, 8.7848e-02],
        [1.8338e-01, 1.5796e-02, 7.7100e-02, 2.4775e-01, 7.0444e-03]])


*Element-wise multiplication*

In [33]:
z = torch.mul(x, y)
print("Element-wise Multiplication:", z)

z = x * y
print("Element-wise Multiplication (*):", z)

Element-wise Multiplication: tensor([ 9, 16, 21])
Element-wise Multiplication (*): tensor([ 9, 16, 21])


*Batch Matrix Multiplication*

In [34]:
batch = 32
n , m, p = 10, 20, 30
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)

print("Batch Matrix Multiplication (first batch):\n", out_bmm[0])
print("Shape of batched multiplication result:", (tensor1 @ tensor2).shape)

Batch Matrix Multiplication (first batch):
 tensor([[5.3150, 5.5166, 4.5463, 4.3658, 4.2593, 4.5562, 4.1952, 5.3552, 4.2603,
         4.9363, 4.1125, 4.6732, 4.8170, 4.5386, 5.1137, 4.0829, 4.6611, 3.6713,
         4.7550, 4.7301, 4.2781, 5.1031, 3.9225, 4.8318, 4.6457, 4.2190, 5.1309,
         5.5011, 4.0109, 2.8352],
        [6.1800, 5.7125, 4.3777, 4.4965, 3.4768, 5.0644, 5.1806, 5.0750, 4.2768,
         5.1937, 4.9714, 5.4069, 5.3882, 5.3743, 5.5494, 4.6129, 5.1022, 3.8722,
         5.4751, 5.0319, 5.0286, 4.3964, 4.1716, 4.3873, 5.1229, 3.6045, 5.3028,
         5.9582, 4.4269, 3.2008],
        [3.9440, 4.3771, 4.6543, 3.4902, 4.3039, 4.5293, 3.4621, 4.9637, 3.8174,
         5.1434, 3.6532, 5.3581, 4.8439, 4.0609, 4.7591, 3.6353, 3.6848, 3.9186,
         4.5961, 4.4345, 4.6415, 4.7196, 4.2054, 4.3534, 4.2138, 4.3329, 4.3962,
         5.2547, 4.4551, 3.6493],
        [5.0619, 5.5438, 4.7315, 4.4756, 4.7456, 5.2352, 4.1619, 4.5960, 4.9203,
         4.8727, 3.8882, 5.6950, 5.1251, 4.6

**Broadcasting and other Useful Operations** 

*Broadcasting automatically expansd smaller tensors to match larger ones in operations*

In [35]:
x1 = torch.rand(5,5)
x2 = torch.rand(5)
print("Tensor x1:\n", x1)
print("Tensor x2:\n", x2)
print("x1 - x2:\n", x1 - x2)
print("x1 raised to the power of x2:\n", x1 ** x2)

Tensor x1:
 tensor([[0.1644, 0.4561, 0.5839, 0.4839, 0.2302],
        [0.3254, 0.7727, 0.1979, 0.0706, 0.7465],
        [0.1204, 0.1465, 0.3205, 0.7154, 0.6798],
        [0.4706, 0.2650, 0.7520, 0.8222, 0.7931],
        [0.4691, 0.1857, 0.1773, 0.6659, 0.7722]])
Tensor x2:
 tensor([0.2601, 0.6265, 0.8055, 0.5305, 0.4569])
x1 - x2:
 tensor([[-0.0957, -0.1704, -0.2216, -0.0467, -0.2267],
        [ 0.0654,  0.1462, -0.6076, -0.4599,  0.2896],
        [-0.1396, -0.4800, -0.4850,  0.1849,  0.2230],
        [ 0.2105, -0.3615, -0.0535,  0.2917,  0.3362],
        [ 0.2090, -0.4408, -0.6282,  0.1353,  0.3153]])
x1 raised to the power of x2:
 tensor([[0.6253, 0.6115, 0.6483, 0.6803, 0.5112],
        [0.7468, 0.8508, 0.2712, 0.2451, 0.8750],
        [0.5767, 0.3002, 0.3999, 0.8372, 0.8384],
        [0.8220, 0.4352, 0.7949, 0.9014, 0.8995],
        [0.8213, 0.3483, 0.2482, 0.8059, 0.8886]])


*Sum of tensor elements along dimension 0*

In [36]:
sum_x = torch.sum(x, dim=0)
print("Sum of x along dim=0:", sum_x)

Sum of x along dim=0: tensor(6)


*Maximum and minimum values*

In [37]:
value, indices = torch.max(x, dim=0)
print("max value and index:", value, indices)

value, indices = torch.min(x, dim=0)
print("min value and index:", value, indices)

max value and index: tensor(3) tensor(2)
min value and index: tensor(1) tensor(0)


*Absolute Values*

In [38]:
print("Absolute value of x:", torch.abs(x))
print("Argmax:", torch.argmax(x, dim=0))
print("Argmin:", torch.argmin(x, dim=0))
print("mean (converted to float):", torch.mean(x.float(), dim=0))
print("Element-wise equality (x == y):", torch.eq(x, y))

Absolute value of x: tensor([1, 2, 3])
Argmax: tensor(2)
Argmin: tensor(0)
mean (converted to float): tensor(2.)
Element-wise equality (x == y): tensor([False, False, False])


*Sorting*

In [39]:
sorted_y, indices = torch.sort(y, dim=0, descending=False)
print("Sorted y and indices:", sorted_y, indices)

Sorted y and indices: tensor([7, 8, 9]) tensor([2, 1, 0])


*Clamping values*

In [40]:
print("Clamped x:", torch.clamp(x, min=0))

Clamped x: tensor([1, 2, 3])


*Boolean operations*

In [41]:
x_bool = torch.tensor([1,0,1,1,1], dtype=torch.bool)
print("Any True:", torch.any(x_bool))
print("All True:", torch.all(x_bool))

Any True: tensor(True)
All True: tensor(False)


**Tensor Indexing**

In [42]:
batch_size = 10
features = 25

x = torch.rand((batch_size, features))

*Access first row*

In [43]:
print("first row of tensor:", x[0, :])

first row of tensor: tensor([0.3466, 0.7510, 0.6374, 0.9642, 0.8499, 0.1479, 0.0237, 0.1587, 0.4767,
        0.0503, 0.0288, 0.7086, 0.8143, 0.6129, 0.0728, 0.6242, 0.1543, 0.9069,
        0.2536, 0.9804, 0.8731, 0.7575, 0.1066, 0.6737, 0.8904])


*Access the second column*

In [44]:
print("second column of tensor:", x[:, 1])

second column of tensor: tensor([0.7510, 0.2068, 0.3985, 0.2294, 0.8614, 0.4038, 0.0424, 0.1820, 0.9212,
        0.2945])


*Access the first 10 elements of the third row*

In [45]:
print("First 10 elements of third row:", x[2, 0:10])

First 10 elements of third row: tensor([0.9129, 0.3985, 0.6402, 0.4488, 0.2022, 0.8033, 0.0296, 0.0906, 0.4965,
        0.3397])


*modify a specific element (set first element to 100)*

In [46]:
x[0, 0] = 100
print(x[0,0])

tensor(100.)


*Fancy indexing example*

In [47]:
x2 = torch.arange(10)
print("Elements where x2 < 2 or x2 > 8:", x2[(x2 < 2) | (x2 > 8)])
print("Even numbers in x2:", x2[(x2 % 2 == 0) & (x2 > 0)])

Elements where x2 < 2 or x2 > 8: tensor([0, 1, 9])
Even numbers in x2: tensor([2, 4, 6, 8])


*Select elements based on conditions*

In [48]:
print("Using torch.where:", torch.where(x2 > 5, x2, x2*2))

Using torch.where: tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])


**Tensor Reshaping**

*Reshape with view() and reshape(), change tensor without altering data.*

In [53]:
x = torch.arange(9)
x_3x3 = x.view(3,3)
print("x:", x)
print("Reshaped x to 3x3 using view:\n", x_3x3)
x_3x3 = x.reshape(3,3)
print("Reshaped x to 3x3 using reshape:\n", x_3x3)
x_1x1 = x.view(1,1,9)
print("Reshaped x to 1x1 using view:\n", x_1x1)

x: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
Reshaped x to 3x3 using view:
 tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
Reshaped x to 3x3 using reshape:
 tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
Reshaped x to 1x1 using view:
 tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8]]])


*Tranpsose and Flatten the tensor*

In [54]:
y = x_3x3.t()
print("Flattened transposed tensor:", y.contiguous().view(9))

Flattened transposed tensor: tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


*Concatenation example*

In [57]:
x1 = torch.rand(2,5)
x2 = torch.rand(2,5)
print("Concatenated along dimension 0 (rows):", torch.cat([x1, x2], dim=0))
print("Concatenated along dimension 1 (columns):", torch.cat([x1, x2], dim=1))
print("Stacked along dimension 0 (rows):", torch.stack([x1, x2], dim=0))

Concatenated along dimension 0 (rows): tensor([[0.1133, 0.2603, 0.0906, 0.9580, 0.6820],
        [0.1679, 0.0597, 0.5028, 0.1183, 0.0216],
        [0.1069, 0.2284, 0.0797, 0.4670, 0.3887],
        [0.0428, 0.5957, 0.8144, 0.7712, 0.9117]])
Concatenated along dimension 1 (columns): tensor([[0.1133, 0.2603, 0.0906, 0.9580, 0.6820, 0.1069, 0.2284, 0.0797, 0.4670,
         0.3887],
        [0.1679, 0.0597, 0.5028, 0.1183, 0.0216, 0.0428, 0.5957, 0.8144, 0.7712,
         0.9117]])
Stacked along dimension 0 (rows): tensor([[[0.1133, 0.2603, 0.0906, 0.9580, 0.6820],
         [0.1679, 0.0597, 0.5028, 0.1183, 0.0216]],

        [[0.1069, 0.2284, 0.0797, 0.4670, 0.3887],
         [0.0428, 0.5957, 0.8144, 0.7712, 0.9117]]])


*Flatten the tensor using view(-1)*

In [58]:
z = x1.view(-1)
print("Flattened tensor shape:", z.shape)

Flattened tensor shape: torch.Size([10])


*Reshape with batch dimension*

In [59]:
batch = 64
x = torch.rand((batch, 2, 5))
print("Reshaped to (batch, -1):", x.view(batch, -1).shape)

Reshaped to (batch, -1): torch.Size([64, 10])


*Permute dimensions - change tensor dimensions efficiently*

In [60]:
z = x.permute(0, 2, 1)
print("Permuted tensor shape:", z.shape)

Permuted tensor shape: torch.Size([64, 5, 2])


*Unsqueeze examples (adding new dimensions)*

In [63]:
x = torch.arange(10)
print("Original x:", x)
print("x unsqueezed at dim 0:", x.unsqueeze(0).shape, x.unsqueeze(0))
print("x unsqueezed at dim 1:", x.unsqueeze(1).shape, x.unsqueeze(1))

Original x: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x unsqueezed at dim 0: torch.Size([1, 10]) tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
x unsqueezed at dim 1: torch.Size([10, 1]) tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
